# Defines the configuration version.
version: "2"

# Reference: https://golangci-lint.run/usage/configuration/
run:
  # Indicates if to include test files or not.
  tests: false
  # Go command is disallowed from the implicit automatic updating of go.mod.
  modules-download-mode: readonly

# Reference: https://golangci-lint.run/docs/linters/configuration/
linters:
  default: none    # Disable all the linters.
  enable:          # Enable specific linter.
    - bodyclose    # Checks whether HTTP response body is closed successfully.
    - dogsled      # Checks assignments with too many blank identifiers.
    - dupl         # Checks for duplicate code.
    - errcheck     # Checking unchecked errors.
    - errorlint    # Used to find code that will cause problems with the error wrapping scheme.
    - gocritic     # Provides diagnostics that check for bugs, performance and style issues.
    - godot        # Checks if comments end in a period.
    - govet        # Examines Go source code and reports suspicious constructs.
    - ineffassign  # Detects when assignments to existing variables are not used.
    - misspell     # Finds commonly misspelled English words.
    - sloglint     # Ensure consistent code style when using log/slog.
    - staticcheck  # Set of rules from staticcheck.
    - unused       # Checks for unused constants, variables, functions, and types.