openapi: 3.1.0

info:
  version: 1.0.0
  title: Warehouse Inventory Management

servers:
  - url: '{address}:{port}/api/{version}'
    description: 'Local'
    variables:
      address:
        default: "http://localhost"
      port:
        default: "8080"
      version:
        default: v1

paths:
  /users:
    get:
      description: Returns all the user from the system.
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'
    post:
      summary: New user account(s)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        '200':
          description: Successfully created new user account(s)
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'
    delete:
      summary: Delete user account
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully deleted the user account
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'
    put:
      summary: Update the user account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        '200':
          description: The user account is successfully updated
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'

  /roles:
    get:
      description: Returns all the roles from the system.
      parameters:
      - name: id
        in: query
        schema:
          type: string
      responses:
        '200':
          description: A list of roles.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/role'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'

components:
  schemas:
    users:
      type: array
      minItems: 1
      maxItems: 10
      uniqueItems: true
      items:
        $ref: '#/components/schemas/user'

    user:
      type: object
      required:
        - role_id
        - first_name
        - last_name
        - password
      properties:
        id:
          type: integer
          format: int32
        role_id:
          type: integer
          format: int32
        first_name:
          type: string
          minLength: 1
        last_name:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 5
          nullable: true
        password:
          type: string
          minLength: 8
          maxLength: 20
        last_login:
          type: string
          nullable: true
        date_created:
          type: string
        date_modified:
          type: string
          nullable: true
    
    roles:
      type: array
      minItems: 1
      maxItems: 10
      uniqueItems: true
      items:
        $ref: '#/components/schemas/role'

    role:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string

    details:
      type: object
      properties:
        message:
          type: string
          nullable: true
        error:
          type: string
          nullable: true
        details:
          type: string
          nullable: true