openapi: 3.1.0

info:
  version: 1.0.0
  title: Warehouse Inventory Management

servers:
  - url: '{address}:{port}/api/{version}'
    description: 'Local'
    variables:
      address:
        default: "http://localhost"
      port:
        default: "8080"
      version:
        default: v1

paths:
  /users:
    get:
      description: Returns all the user from the system
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: New user account(s)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        '200':
          description: Successfully created new user account(s)
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete user account
      parameters:
      - name: id
        in: query
        required: true
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update the user account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /roles:
    get:
      description: Returns either all/specific role(s) from the system
      parameters:
      - name: id
        in: query
      responses:
        '200':
          description: A list of roles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/roles'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: New role(s)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/roles'
      responses:
        '200':
          description: Successfully created new role(s)
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete user role
      parameters:
      - name: id
        in: query
        required: true
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update the role
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/roles'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /storages:
    get:
      description: Returns either all/specific storage(s) from the system
      parameters:
      - name: id
        in: query
      responses:
        '200':
          description: Succesfully retrieved all/specific storage(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/storages'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: New storage(s)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/storages'
      responses:
        '200':
          description: Successfully created new storage(s)
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete storage
      parameters:
      - name: id
        in: query
        required: true
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update the storage details
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/storages'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /uoms:
    get:
      description: Returns either all/specific unit of measurement(s) from the system.
      parameters:
      - name: id
        in: query
      responses:
        '200':
          description: Succesfully retrieved all/specific unit of measurement(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uoms'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: New unit of measurement(s)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/uoms'
      responses:
        '200':
          description: Successfully created new unit of measurement(s)
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete a specific unit of measurement
      parameters:
      - name: id
        in: query
        required: true
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update the unit of measurement details
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/uoms'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /items:
    get:
      description: Returns either all/specific item from the system.
      parameters:
      - name: id
        in: query
      responses:
        '200':
          description: Successfully retrieved all/specific item(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/items'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: New item(s)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/items'
        responses:
          '200':
            description: Successfully created new item(s)
          '400':
            $ref: '#/components/responses/BadRequest'
          '500':
            $ref: '#/components/responses/InternalServerERror'
    delete:
      summary: Delete a specific item
      parameters:
      - name: id
        in: query
        required: true
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update the item(s) details
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schema/items'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  responses:
    OK:
      description: The request is successfully executed

    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#componentns/schemas/details'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/details'

  schemas:
    users:
      type: array
      minItems: 1
      maxItems: 10
      uniqueItems: true
      items:
        $ref: '#/components/schemas/user'

    user:
      type: object
      required:
        - role_id
        - first_name
        - last_name
        - password
      properties:
        id:
          type: integer
          format: int32
        role_id:
          type: integer
          format: int32
        first_name:
          type: string
          minLength: 1
        last_name:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 5
          nullable: true
        password:
          type: string
          minLength: 8
          maxLength: 20
        last_login:
          type: string
          nullable: true
        date_created:
          type: string
        date_modified:
          type: string
          nullable: true
    
    roles:
      type: array
      minItems: 1
      maxItems: 10
      uniqueItems: true
      items:
        $ref: '#/components/schemas/role'

    role:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string

    storages:
      type: array
      minItems: 1
      maxItems: 10
      uniqueItems: true
      items:
        $ref: '#/components/schemas/storage'

    storage:
      type: object
      required:
        - code
        - name
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        code:
          type: string
        description:
          type: string

    uoms:
      type: array
      minItems: 1
      maxItems: 10
      uniqueItems: true
      items:
        $ref: '#/components/schemas/uom'

    uom:
      type: object
      required:
        - code
        - name
      properties:
        id:
          type: integer
          format: int32
        code:
          type: string
        name:
          type: string

    items:
      type: array
      minItems: 1
      maxItems: 10
      uniqueItems: true
      items:
        $ref: '#/components/schemas/item'

    item:
      type: object
      required:
        - name
        - storage_id
        - quantity
        - unit_price
        - uom_id
        - created_by
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        storage_id:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        unit_price:
          type: number
          format: double
        uom_id:
          type: integer
          format: int32
        created_by:
          type: integer
          format: int32
          description: unique id of the user
        date_created:
          type: string
          format: date-time
        date_modified:
          type: string
          format: date-time

    details:
      type: object
      properties:
        message:
          type: string
          nullable: true
        error:
          type: string
          nullable: true
        details:
          type: string
          nullable: true